name: Build & Deploy to DockerHub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20" # Use your project's Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run Jest tests
        run: npm test # or use `npx jest` if not set in package.json
        env:
          DB_URI: ${{ secrets.DB_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
          PORT: ${{ secrets.PORT }}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/networth-tracker-backend:latest

      - name: Verify the pushed docker image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/networth-tracker-backend:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo docker pull sagar246/networth-tracker-backend:latest
            sudo docker stop sagar246/networth-tracker-backend || true
            sudo docker rm sagar246/networth-tracker-backend || true
            sudo docker run -d --name sagar246/networth-tracker-backend -p 1337:1337 \
              -e DB_URI="${{ secrets.DB_URI }}" \
              -e PORT="${{ secrets.PORT }}" \
              -e JWT_SECRET="${{ secrets.JWT_SECRET }}" \
              -e ENCRYPTION_KEY="${{ secrets.ENCRYPTION_KEY}}" \
              sagar246/networth-tracker-backend:latest
